CREATE TABLE `settings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`clinicName` varchar(255) NOT NULL,
	`clinicEmail` varchar(320),
	`clinicPhone` varchar(20),
	`clinicAddress` text,
	`clinicCity` varchar(100),
	`clinicState` varchar(2),
	`clinicZipCode` varchar(10),
	`ownerName` varchar(255),
	`ownerEmail` varchar(320),
	`ownerPhone` varchar(20),
	`ownerCPF` varchar(14),
	`ownerCRPNumber` varchar(20),
	`sessionDefaultDuration` int NOT NULL DEFAULT 60,
	`sessionDefaultPrice` decimal(10,2),
	`currency` varchar(3) NOT NULL DEFAULT 'BRL',
	`timezone` varchar(50) NOT NULL DEFAULT 'America/Sao_Paulo',
	`language` varchar(10) NOT NULL DEFAULT 'pt-BR',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `settings_id` PRIMARY KEY(`id`),
	CONSTRAINT `settings_userId_unique` UNIQUE(`userId`)
);
