CREATE TABLE `anamnesis_intake` (
	`id` int AUTO_INCREMENT NOT NULL,
	`patientId` int NOT NULL,
	`userId` int NOT NULL,
	`intakeType` enum('initial_assessment','follow_up','reassessment') NOT NULL DEFAULT 'initial_assessment',
	`maritalStatus` varchar(64),
	`numberOfChildren` int,
	`livingArrangement` varchar(255),
	`education` varchar(255),
	`chiefComplaint` text,
	`historyOfPresentIllness` text,
	`pastMedicalHistory` text,
	`pastPsychiatricHistory` text,
	`familyHistory` text,
	`substanceUse` text,
	`sleepPatterns` text,
	`dietAndExercise` text,
	`stressFactors` text,
	`mentalStatusExam` text,
	`moodAndAffect` varchar(255),
	`cognitiveFunction` text,
	`suicidalityAssessment` text,
	`preliminaryDiagnosis` text,
	`treatmentPlan` text,
	`recommendedTherapy` varchar(255),
	`questionnaireResponses` text,
	`status` enum('in_progress','completed','archived') NOT NULL DEFAULT 'in_progress',
	`completedAt` bigint,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `anamnesis_intake_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `medical_records_timeline` (
	`id` int AUTO_INCREMENT NOT NULL,
	`patientId` int NOT NULL,
	`sessionId` int,
	`userId` int NOT NULL,
	`entryType` enum('session_note','clinical_evolution','intervention','assessment','treatment_plan','discharge_summary') NOT NULL,
	`title` varchar(255) NOT NULL,
	`content` text NOT NULL,
	`clinicalEvolution` text,
	`interventionSummary` text,
	`attachments` text,
	`tags` text,
	`isPrivate` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `medical_records_timeline_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `technical_documents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`patientId` int NOT NULL,
	`userId` int NOT NULL,
	`documentType` enum('certificate','report','opinion','referral','prescription','evaluation') NOT NULL,
	`title` varchar(255) NOT NULL,
	`templateId` varchar(64),
	`content` text NOT NULL,
	`pdfUrl` varchar(1024),
	`pdfKey` varchar(512),
	`status` enum('draft','pending_review','approved','signed','archived') NOT NULL DEFAULT 'draft',
	`signatureDate` bigint,
	`issuedDate` bigint NOT NULL,
	`expiryDate` bigint,
	`metadata` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `technical_documents_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `treatment_plans` (
	`id` int AUTO_INCREMENT NOT NULL,
	`patientId` int NOT NULL,
	`userId` int NOT NULL,
	`anamnesisId` int,
	`title` varchar(255) NOT NULL,
	`goals` text,
	`interventions` text,
	`expectedDuration` int,
	`frequency` varchar(64),
	`startDate` bigint NOT NULL,
	`expectedEndDate` bigint,
	`actualEndDate` bigint,
	`status` enum('active','paused','completed','discontinued') NOT NULL DEFAULT 'active',
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `treatment_plans_id` PRIMARY KEY(`id`)
);
