CREATE TABLE `anamnese_backup` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`patientId` int NOT NULL,
	`bloodType` varchar(10),
	`allergies` longtext,
	`chronicConditions` longtext,
	`disabilities` longtext,
	`mainComplaintDetail` longtext,
	`currentDiseaseHistory` longtext,
	`psychiatricHistory` longtext,
	`familyHistory` longtext,
	`personalHistory` longtext,
	`childhoodHistory` longtext,
	`relationshipHistory` longtext,
	`professionalHistory` longtext,
	`substanceUse` longtext,
	`sleepAndEating` longtext,
	`sexualAffectiveLife` longtext,
	`previousTreatments` longtext,
	`therapeuticGoals` longtext,
	`cidCode` varchar(255),
	`cidDescription` varchar(255),
	`therapeuticApproach` varchar(500),
	`riskFactors` longtext,
	`protectiveFactors` longtext,
	`additionalNotes` longtext,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `anamnese_backup_id` PRIMARY KEY(`id`)
);
