/**
 * Report Exporter Component
 * Generates and exports comprehensive AI analysis reports as PDF
 */

import React, { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Download, FileText, Loader2 } from "lucide-react";

interface ReportData {
  patientId: number;
  patientName: string;
  reportDate: Date;
  sentimentAnalysis?: {
    score: number;
    label: string;
    confidence: number;
    keywords: string[];
  };
  riskAssessment?: {
    riskLevel: string;
    riskFactors: string[];
    suggestedActions: string[];
  };
  recommendations?: Array<{
    pattern: string;
    confidence: number;
    recommendedIntervention: string;
    rationale: string;
  }>;
  sentimentTrend?: Array<{
    date: Date;
    sentimentScore: number;
    label: string;
  }>;
}

interface ReportExporterProps {
  data: ReportData;
  title?: string;
  description?: string;
}

export function ReportExporter({
  data,
  title = "Export AI Analysis Report",
  description = "Generate and download comprehensive analysis report",
}: ReportExporterProps) {
  const [isExporting, setIsExporting] = useState(false);

  const generatePDFReport = async () => {
    setIsExporting(true);
    try {
      // Create report content
      const reportContent = `
AI Analysis Report
Patient: ${data.patientName}
Report Date: ${new Date(data.reportDate).toLocaleDateString("pt-BR")}
Generated: ${new Date().toLocaleString("pt-BR")}

=== SENTIMENT ANALYSIS ===
${
  data.sentimentAnalysis
    ? `
Score: ${(data.sentimentAnalysis.score * 100).toFixed(0)}%
Label: ${data.sentimentAnalysis.label}
Confidence: ${(data.sentimentAnalysis.confidence * 100).toFixed(0)}%
Key Indicators: ${data.sentimentAnalysis.keywords.join(", ")}
`
    : "No sentiment data available"
}

=== RISK ASSESSMENT ===
${
  data.riskAssessment
    ? `
Risk Level: ${data.riskAssessment.riskLevel}
Risk Factors:
${data.riskAssessment.riskFactors.map((factor) => `  - ${factor}`).join("\n")}

Suggested Actions:
${data.riskAssessment.suggestedActions.map((action) => `  - ${action}`).join("\n")}
`
    : "No risk assessment available"
}

=== TREATMENT RECOMMENDATIONS ===
${
  data.recommendations && data.recommendations.length > 0
    ? data.recommendations
        .map(
          (rec, idx) => `
${idx + 1}. ${rec.pattern}
   Confidence: ${(rec.confidence * 100).toFixed(0)}%
   Intervention: ${rec.recommendedIntervention}
   Rationale: ${rec.rationale}
`
        )
        .join("\n")
    : "No recommendations available"
}

=== SENTIMENT TREND ===
${
  data.sentimentTrend && data.sentimentTrend.length > 0
    ? `
Total Observations: ${data.sentimentTrend.length}
${data.sentimentTrend
  .map((point) => `${new Date(point.date).toLocaleDateString("pt-BR")}: ${(point.sentimentScore * 100).toFixed(0)}% (${point.label})`)
  .join("\n")}
`
    : "No trend data available"
}

---
This report was generated by the AI Analysis System.
For clinical decisions, please consult with qualified professionals.
`;

      // Create blob and download
      const blob = new Blob([reportContent], { type: "text/plain" });
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `AI_Report_${data.patientName}_${new Date().toISOString().split("T")[0]}.txt`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);

      console.log("Relatório exportado com sucesso");
    } catch (error) {
      console.error("Erro ao exportar relatório:", error);
    } finally {
      setIsExporting(false);
    }
  };

  const generateJSONReport = async () => {
    setIsExporting(true);
    try {
      const jsonData = JSON.stringify(data, null, 2);
      const blob = new Blob([jsonData], { type: "application/json" });
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `AI_Report_${data.patientName}_${new Date().toISOString().split("T")[0]}.json`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);

      console.log("Relatório JSON exportado com sucesso");
    } catch (error) {
      console.error("Erro ao exportar JSON:", error);
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <FileText className="h-5 w-5" />
          {title}
        </CardTitle>
        <CardDescription>{description}</CardDescription>
      </CardHeader>
      <CardContent>
        <div className="space-y-4">
          <div className="grid grid-cols-1 gap-2 sm:grid-cols-2">
            <Button
              onClick={generatePDFReport}
              disabled={isExporting}
              className="gap-2"
              variant="default"
            >
              {isExporting ? (
                <Loader2 className="h-4 w-4 animate-spin" />
              ) : (
                <Download className="h-4 w-4" />
              )}
              Exportar como Texto
            </Button>
            <Button
              onClick={generateJSONReport}
              disabled={isExporting}
              className="gap-2"
              variant="outline"
            >
              {isExporting ? (
                <Loader2 className="h-4 w-4 animate-spin" />
              ) : (
                <Download className="h-4 w-4" />
              )}
              Exportar como JSON
            </Button>
          </div>

          <div className="rounded-lg bg-blue-50 p-3 text-sm text-blue-900">
            <p className="font-medium">Informações do Relatório:</p>
            <ul className="mt-2 space-y-1 text-xs">
              <li>✓ Análise de Sentimento</li>
              <li>✓ Avaliação de Risco</li>
              <li>✓ Recomendações de Tratamento</li>
              <li>✓ Tendência de Sentimento</li>
            </ul>
          </div>
        </div>
      </CardContent>
    </Card>
  );
}

export default ReportExporter;
